### ISSUE TITLE
Release details 0.2.3

### ISSUE THREAD

**Issue by petrrr** [amaggi/waveloc#103]
I admit that this might sound a bit pedantic. But I have some doubt about the releases of waveloc. 
It looks like the last release (at least formally) is 0.2.2. However, master looks very much like a 0.2.3 release already, also considering there a devel branch and specific branches for specific developments. Still 0.2.3 has no tag or frozen release tarball. So is there some further development to be expected?

I also wonder about the status of the u-grid branch. I am guessing this is still WIP. But is it already at some state where this could be started to use (of cause with caution). 

Thanks for clarification.

**Comment by petrrr** [comment]
Okay, I see there is a tarball for 0.2.3 on https://s3.amazonaws.com/waveloc/waveloc-0.2.3.tar.gz.
So I'd assume this is formally release, only that the tag in the repo is missing.

**Comment by amaggi** [comment]
Yes, 0.2.3 is the formal release, and yes, I forgot to tag the repo... my bad. I'll fix that soon.

Regarding the u-grid branch : coding is pretty much complete, and I've been updating the tests as I've been going along, so I'm pretty confident that the results given by this version - which uses unstructured grids - are equivalent to those given by the fixed grid implemented in the previous versions. The sticking point at the moment is the plotting of cuts through the 3D volume.

**Comment by amaggi** [comment]
waveloc-0.2.3 is now tagged and released.
